[tool.poetry]
name = "upm"
version = "0.1.0"
description = ""
authors = ["Eris9 <cool5tarxv@gmail.com>"]

[tool.poetry.dependencies]
requests = "^1.0"
lxml = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
